### PR TITLE
Labels

### PR DESCRIPTION
**Pull request by achamayou**
Add labels on bars, and tweak colours slightly for a slightly more subdued look.

Edit: ignore commit history, will squash.

### CODE REVIEW

**Comment by ghost** [comment]
images

**Comment by letmaik** [comment]
How about including the master values as well? I know it's redundant but it would make it easier to imagine the diff. Maybe "0.018 -> 0.022". Depending on how long the bar is you could either do it like you do now or move the text inside the bar.

**Comment by achamayou** [comment]
@letmaik I did try that (if you scroll around the closed PR you will see it), but it looked very busy and I did not find a way to fix it. I am now wondering if putting the reference value in the labels on the left would be better/

I'm slightly wary of the -> notation in particular because although that's accurate now, once we move to an ewma it's a bit more complicated than a direct transition.

Putting the text inside the bars is only possible when they are big enough, it involves a bunch of extra computation and means that we won't have a consistent display, so I'm not super fond of it. I can be done though.

**Comment by letmaik** [comment]
OK let's leave it like it is for now. Displaying a single reference value for ewma probably doesn't make much sense anyway.

**Review by letmaik — APPROVED** [review]

**Review by jumaffre — APPROVED** [review]

**Pull request merged**
