### PR TITLE
Include branch/pr history in table

### LINKED ISSUE #123: Table doesn't show PR/branch entries
Currently, only entries from the target branch are shown.

I think dumping the PR/branch entries as a second table in the same details block is probably the easiest and also gives some separation.

### PR DESCRIPTION
**Pull request by letmaik**
Fixes #123.

### CODE REVIEW

**Comment by ghost** [comment]
letmaik/branch-history-table@[732 aka 20211207.3](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=732&view=results) vs main ewma over 2 builds from [2](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=2&view=results) to [725](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=725&view=results)
<details>
  <summary>Click to see table</summary>
  
  main
  
  |   build_id | build_number   |   Throughput (tx/s) ^ |   Latency (ms) |   Peak working set size (GB) |   Accuracy (%) ^ |   Error rate (%) |   Memory fragmentation (%) |   CPU usage (%) |   New metric (U) |
|-----------:|:---------------|----------------------:|---------------:|-----------------------------:|-----------------:|-----------------:|---------------------------:|----------------:|-----------------:|
|          2 | 0000.0         |                 48992 |             10 |                           49 |             0.73 |             0.05 |                      0.022 |            0.3  |              169 |
|        725 | 20211130.3     |                 51282 |             11 |                           49 |             0.69 |             0.05 |                      0.021 |            0.32 |              158 |
  
  letmaik/branch-history-table

|   build_id | build_number   |   Throughput (tx/s) ^ |   Latency (ms) |   Peak working set size (GB) |   Accuracy (%) ^ |   Error rate (%) |   Memory fragmentation (%) |   CPU usage (%) |   New metric (U) |
|-----------:|:---------------|----------------------:|---------------:|-----------------------------:|-----------------:|-----------------:|---------------------------:|----------------:|-----------------:|
|        729 | 20211206.4     |                 46638 |              9 |                           47 |             0.7  |             0.05 |                      0.022 |            0.32 |              124 |
|        731 | 20211207.2     |                 46818 |             10 |                           49 |             0.72 |             0.05 |                      0.018 |            0.3  |              194 |
|        732 | 20211207.3     |                 46474 |             11 |                           50 |             0.73 |             0.06 |                      0.021 |            0.31 |              128 |
</details>

images

**Review by achamayou — APPROVED** [review]
LGTM although I'd be tempted to add a header on each table to make it clear which is which. Mostly you'll be able to tell from the size but not always?

**Comment by letmaik** [comment]
> LGTM although I'd be tempted to add a header on each table to make it clear which is which. Mostly you'll be able to tell from the size but not always?

How about now?

**Review by jumaffre — APPROVED** [review]

**Pull request merged**
