### PR TITLE
Capture build number

### PR DESCRIPTION
**Pull request by achamayou**
For some reason I thought we did this already, and we could just display them in xticks. Apparently not. So let's do it.

### CODE REVIEW

**Comment by ghost** [comment]
capture_build_numbers@[550 aka 20200503.1](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=550&view=results) vs master ewma over 34 builds from [445](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=445&view=results) to [548](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=548&view=results)
images

**Comment by letmaik** [comment]
Keep in mind that build number is customizable, so this should probably be optional whether to add it as tick labels.

**Comment by letmaik** [comment]
On the other hand, it is the thing that is displayed in DevOps (build id is only in the URL afaik), so I would actually use the build number exclusively in texts: capture_build_numbers@20200503.1 vs master ewma over 34 builds from 20200403.1 to 20200502.1

**Comment by achamayou** [comment]
Yes, I think that’s the way to go, it’s the user-visible name of the build. The build id is still convenient for sorting and of course to link to actual build pages.

**Pull request merged**
