### PR TITLE
Can introduce new or delete existing metrics 

### LINKED ISSUE #31: It should be possible to introduce new metrics on a branch
This is currently forbidden by https://github.com/jumaffre/cimetrics/blob/master/cimetrics/plot.py#L66

When metrics are on target but not branch, they should not be displayed. When metrics are on branch but not target, they should be displayed, and their target value should be assumed to be the same as their branch value (ie. 0% change).

### PR DESCRIPTION
**Pull request by jumaffre**
Resolves https://github.com/jumaffre/cimetrics/issues/31.

### CODE REVIEW

**Comment by ghost** [comment]
images

**Review by achamayou — APPROVED** [review]

**Comment by achamayou** [comment]
Value doesn’t display?

**Comment by jumaffre** [comment]
> Value doesn’t display?

Doesn't look like we display the value when reference = branch? (e.g. `CPU Usage`)

**Comment by achamayou** [comment]
That’s probably not a good idea when introducing new metrics. I think it possibly made sense when « there’s no change », but that’s probably rare and even so, I think it’s outweighed by the new metrics case.

**Comment by achamayou** [comment]
I can look at this separately.

**Comment by jumaffre** [comment]
I'll merge this as is then!

**Pull request merged**
