### PR TITLE
Fix rebuild in azp

### PR DESCRIPTION
**Pull request by achamayou**
Raised in https://github.com/microsoft/CCF/issues/347

### CODE REVIEW

**Comment by ghost** [comment]
images

**Comment by ghost** [comment]
images

**Comment by jumaffre** [comment]
For the latest build on this PR, `BUILD_SOURCEBRANCH=refs/pull/37/merge`. It doesn't seem that we want to use `37/merge` for the name of this branch? Also, it looks like the metrics weren't pushed as the run was not considered a PR?

image

**Comment by achamayou** [comment]
@jumaffre previously, this build would have thrown an exception during upload (see ticket linked above), but I agree it would be better to categorise it as a PR build and use the full branch name if possible.

**Comment by jumaffre** [comment]
> @jumaffre previously, this build would have thrown an exception during upload (see ticket linked above), but I agree it would be better to categorise it as a PR build and use the full branch name if possible.

I think we could check that the build is manual (`BUILD_REASON=Manual`), then look at `BUILD_SOURCEBRANCH` to check whether it contains "pull" (e.g. `refs/pull/37/merge`) and extract the PR number from it as well. 

But still, from this, there's no easy way/env var to retrieve the source and target branches as the build is categorised as manual with only the commit hashes of the source and target (e.g. `Merge 676b05d18dc6cd3244bed102e356915c583b3c32 into f936f2aa0aa984566c83723c5b7b6e27386d72cd`). Of course, we could look up existing cimetrics results for this PR and use the same source and target branches for this build as well. What do you think?

**Comment by achamayou** [comment]
@jumaffre so there are two things I think, one is whether we crash on collection in these circumstances, and this fixes that. The other is whether we can correctly figure out the src and tgt branches and report the changes correctly. What you suggest sounds good, I'll look into it.

**Comment by achamayou** [comment]
So we don't currently store the PR ID, and as a consequence there isn't really an easy way to connect those builds with earlier values as far as I can tell.

**Comment by jumaffre** [comment]
> So we don't currently store the PR ID, and as a consequence there isn't really an easy way to connect those builds with earlier values as far as I can tell.

OK. I propose that we create an issue for this/add a TODO in the code and merge this PR as is so that at least manual builds of PR stop failing?

**Review by jumaffre — APPROVED** [review]

**Comment by achamayou** [comment]
Yes, I think we could log SYSTEM_PULLREQUEST_PULLREQUESTNUMBER when it's defined, and perhaps fall back to using that for linkage on those manual merge builds. I think we could use that to generate and publish as build artifacts the diff, but I'm not sure about pushing it to PR (is it always the case that there is a corresponding PR open?).

**Pull request merged**
