### PR TITLE
Sketch build history

### PR DESCRIPTION
**Pull request by achamayou**
More hacking of the trend view, for #60

### CODE REVIEW

**Comment by achamayou** [comment]
The ready for review bit is a lie, but I want the CI to run, and what's ready for discussion rather than review is the rendered output.

**Comment by ghost** [comment]
history@[428 aka 20200129.12](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=428&view=results) vs master ewma over 30 builds from [245](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=245&view=results) to [408](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=408&view=results)
images

**Comment by achamayou** [comment]
So one thing that's missing is checking the PR id, to avoid picking up changes from the same named branch with a different PR id. I pushed a bunch of changes for this branch from a local run, and so they got picked up, but they could have been from a much older branch called "history" too, and that wouldn't have been what we wanted.

I've also capped the suffix history to 5 values, because that seemed like a nice round number, but it may not be the right round number.

**Comment by achamayou** [comment]
I am wondering if it's a good idea to semantically colour all the branch bars, or if it is distracting and we would be better off with a neutral colour similar to but of course not identical to that of the target. That way there'd be only one colour left, which is the colour for the last value.

Or maybe this is fine, it just looks silly now because the values are random, and that's ok. On a real directional change, the colour will mostly be one way.

**Comment by jumaffre** [comment]
Just a thought: could we try to differentiate the latest run from the other runs on that branch (e.g. dotted line for all the other runs on the branch, full line from the latest run). I think the colours for each run is still somewhat useful but the current display makes my brain hurt a little bit. Awesome work though!

**Comment by achamayou** [comment]
Yeah agreed, that's why I was wondering about changing the color. I'll try dotted but I'm worried about what happens to really short lines, another alternative might be alpha (ie. fade old builds down to 50% or something).

**Comment by achamayou** [comment]
Another thing I hadn't though of is that it looks a lot like the target branch actual data points

image

Of course we could represent them as actual data points (single circles), which would be both consistent and fairly light?

**Comment by jumaffre** [comment]
I quite like the dotted line. I still think the last build could be a solid line to give it a little more importance. I think the single-circle branch build will look too much like the target branch? It might be worth trying if it's not too painful.

**Comment by achamayou** [comment]
Updated with single points now, plus some WIP cleanup of the code. Unfinished.

**Comment by jumaffre** [comment]
> Updated with single points now, plus some WIP cleanup of the code. Unfinished.

Dotted lines are my favourite so far. I find single dots a little awkward to read as their X-axis coordinates are very close to each other.

**Comment by achamayou** [comment]
Ok, I'll go with that then. I'll also wrap up the refactoring, we can get rid of a bunch more code.

**Comment by achamayou** [comment]
@jumaffre ok I think I'm happy with this now. Something bad seems to have happened to the CI, but I'm not sure what, I'll take a look tomorrow.

**Comment by achamayou** [comment]
Weird, it's as if the connection string was wrong (but it works from my box). Switching to the secondary doesn't help either.

**Comment by achamayou** [comment]
Odd, the availability of secrets to builds from forks on PR issued by members had been removed. Anyway, I put it back now.

**Comment by achamayou** [comment]
Github token had gone too apparently, weird.

**Comment by achamayou** [comment]
Ok that's enough tweaking. No more tweaking until someone else reviews!

**Review by jumaffre — APPROVED** [review]
Looks awesome! Nice refactoring too 👍

**Pull request merged**
