### PR TITLE
Automated release

### LINKED ISSUE #33: Document/automate pypi release

### PR DESCRIPTION
**Pull request by jumaffre**
Automated release of tagged commits to https://pypi.org/project/cimetrics/. 
Tags should start with `v`, e.g. `v0.2.0`. 

Resolves https://github.com/jumaffre/cimetrics/issues/33

### CODE REVIEW

**Comment by ghost** [comment]
images

**Comment by letmaik** [comment]
I would do an alpha release (e.g. 0.1.0a1) in this PR to check that it works. This will not automatically be picked up by pip install.

**Comment by jumaffre** [comment]
@letmaik That's exactly why I did a few commits ago: https://pypi.org/project/cimetrics/0.2.1a1/

**Comment by letmaik** [comment]
Great, then I'd say it's all good :)

**Comment by jumaffre** [comment]
Excellent. Thanks for your help! 👍

**Review by achamayou — APPROVED** [review]
That's awesome and beautifully simple, thank you!

**Pull request merged**
