### PR TITLE
Anomaly xticks when monitoring

### PR DESCRIPTION
**Pull request by achamayou**
Tried yticks too but it's too busy and not very nice. I think they'd be better annotated in place instead, or possibly near the top of the anomaly vertical bar?

Also the xticks labels should be build numbers (YYYYMMDD.N) rather than build ids. This requires a bit of reshuffling of the data format, but will be much nicer to read.

Something that could be nice would be displaying the last merged PR ID underneath as well, but that's data we don't have right now.

### CODE REVIEW

**Comment by ghost** [comment]
monitor_xticks@[546 aka 20200425.2](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=546&view=results) vs master ewma over 32 builds from [445](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=445&view=results) to [543](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=543&view=results)
images

**Comment by achamayou** [comment]
I think I'm happy with this, but feedback welcome as always:

image

**Comment by jumaffre** [comment]
Neat! 

Just to confirm my understanding is right:
image

Build `464` performance was `5.1e1` but the next build (build ID unknown, but somewhere between `464` and `543`) introduced a regression according to the internal anomaly detection of cimetrics? 

Would it be nice to know how much the regression was (in %) - not necessarily in this PR though!

**Comment by achamayou** [comment]
The number displayed right now is the ewm rather than the raw value. 464 here is the first build of the anomaly, but it can't be interpreted strictly, it may have gone down some because of noise, it's only with enough of a window that we can tell this is the new normal.

That's why I think we want ewm values, we want to know the ewm before each anomaly, roughly speaking (the value after is either the final value, or the before value of the next anomaly).

**Comment by jumaffre** [comment]
OK that makes perfect sense to me. Let's give this a try 👍

**Review by jumaffre — APPROVED** [review]

**Comment by achamayou** [comment]
So technically the anomalies are ranges, we could try to display a before/after value. I think that should still be based on the ewm though, rather than on potentially noisy individual values. I'm going to push this for now so we can see the results on CCF, and I'll iterate in further PRs.

**Pull request merged**
